name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there! I see that you just opened your first issue! Good luck!'
        pr-message: 'Hi there! I see that you just opened your first pull request! Good luck!'
